// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: framing.proto

package pbstream

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ConnectionHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Multiplex bool `protobuf:"varint,1,opt,name=multiplex,proto3" json:"multiplex,omitempty"`
}

func (x *ConnectionHeader) Reset() {
	*x = ConnectionHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framing_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnectionHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnectionHeader) ProtoMessage() {}

func (x *ConnectionHeader) ProtoReflect() protoreflect.Message {
	mi := &file_framing_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnectionHeader.ProtoReflect.Descriptor instead.
func (*ConnectionHeader) Descriptor() ([]byte, []int) {
	return file_framing_proto_rawDescGZIP(), []int{0}
}

func (x *ConnectionHeader) GetMultiplex() bool {
	if x != nil {
		return x.Multiplex
	}
	return false
}

type RPCHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Selector string `protobuf:"bytes,1,opt,name=selector,proto3" json:"selector,omitempty"`
}

func (x *RPCHeader) Reset() {
	*x = RPCHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framing_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCHeader) ProtoMessage() {}

func (x *RPCHeader) ProtoReflect() protoreflect.Message {
	mi := &file_framing_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCHeader.ProtoReflect.Descriptor instead.
func (*RPCHeader) Descriptor() ([]byte, []int) {
	return file_framing_proto_rawDescGZIP(), []int{1}
}

func (x *RPCHeader) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type RPCFooter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//	*RPCFooter_Success_
	//	*RPCFooter_Error_
	Response isRPCFooter_Response `protobuf_oneof:"response"`
}

func (x *RPCFooter) Reset() {
	*x = RPCFooter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framing_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCFooter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCFooter) ProtoMessage() {}

func (x *RPCFooter) ProtoReflect() protoreflect.Message {
	mi := &file_framing_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCFooter.ProtoReflect.Descriptor instead.
func (*RPCFooter) Descriptor() ([]byte, []int) {
	return file_framing_proto_rawDescGZIP(), []int{2}
}

func (m *RPCFooter) GetResponse() isRPCFooter_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *RPCFooter) GetSuccess() *RPCFooter_Success {
	if x, ok := x.GetResponse().(*RPCFooter_Success_); ok {
		return x.Success
	}
	return nil
}

func (x *RPCFooter) GetError() *RPCFooter_Error {
	if x, ok := x.GetResponse().(*RPCFooter_Error_); ok {
		return x.Error
	}
	return nil
}

type isRPCFooter_Response interface {
	isRPCFooter_Response()
}

type RPCFooter_Success_ struct {
	Success *RPCFooter_Success `protobuf:"bytes,1,opt,name=success,proto3,oneof"`
}

type RPCFooter_Error_ struct {
	Error *RPCFooter_Error `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*RPCFooter_Success_) isRPCFooter_Response() {}

func (*RPCFooter_Error_) isRPCFooter_Response() {}

type RPCStreamHeader struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Operation:
	//	*RPCStreamHeader_Continue_
	//	*RPCStreamHeader_Footer
	Operation isRPCStreamHeader_Operation `protobuf_oneof:"operation"`
}

func (x *RPCStreamHeader) Reset() {
	*x = RPCStreamHeader{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framing_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCStreamHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCStreamHeader) ProtoMessage() {}

func (x *RPCStreamHeader) ProtoReflect() protoreflect.Message {
	mi := &file_framing_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCStreamHeader.ProtoReflect.Descriptor instead.
func (*RPCStreamHeader) Descriptor() ([]byte, []int) {
	return file_framing_proto_rawDescGZIP(), []int{3}
}

func (m *RPCStreamHeader) GetOperation() isRPCStreamHeader_Operation {
	if m != nil {
		return m.Operation
	}
	return nil
}

func (x *RPCStreamHeader) GetContinue() *RPCStreamHeader_Continue {
	if x, ok := x.GetOperation().(*RPCStreamHeader_Continue_); ok {
		return x.Continue
	}
	return nil
}

func (x *RPCStreamHeader) GetFooter() *RPCFooter {
	if x, ok := x.GetOperation().(*RPCStreamHeader_Footer); ok {
		return x.Footer
	}
	return nil
}

type isRPCStreamHeader_Operation interface {
	isRPCStreamHeader_Operation()
}

type RPCStreamHeader_Continue_ struct {
	Continue *RPCStreamHeader_Continue `protobuf:"bytes,1,opt,name=continue,proto3,oneof"`
}

type RPCStreamHeader_Footer struct {
	Footer *RPCFooter `protobuf:"bytes,2,opt,name=footer,proto3,oneof"`
}

func (*RPCStreamHeader_Continue_) isRPCStreamHeader_Operation() {}

func (*RPCStreamHeader_Footer) isRPCStreamHeader_Operation() {}

type RPCFooter_Success struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RPCFooter_Success) Reset() {
	*x = RPCFooter_Success{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framing_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCFooter_Success) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCFooter_Success) ProtoMessage() {}

func (x *RPCFooter_Success) ProtoReflect() protoreflect.Message {
	mi := &file_framing_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCFooter_Success.ProtoReflect.Descriptor instead.
func (*RPCFooter_Success) Descriptor() ([]byte, []int) {
	return file_framing_proto_rawDescGZIP(), []int{2, 0}
}

type RPCFooter_Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *RPCFooter_Error) Reset() {
	*x = RPCFooter_Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framing_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCFooter_Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCFooter_Error) ProtoMessage() {}

func (x *RPCFooter_Error) ProtoReflect() protoreflect.Message {
	mi := &file_framing_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCFooter_Error.ProtoReflect.Descriptor instead.
func (*RPCFooter_Error) Descriptor() ([]byte, []int) {
	return file_framing_proto_rawDescGZIP(), []int{2, 1}
}

func (x *RPCFooter_Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type RPCStreamHeader_Continue struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RPCStreamHeader_Continue) Reset() {
	*x = RPCStreamHeader_Continue{}
	if protoimpl.UnsafeEnabled {
		mi := &file_framing_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RPCStreamHeader_Continue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RPCStreamHeader_Continue) ProtoMessage() {}

func (x *RPCStreamHeader_Continue) ProtoReflect() protoreflect.Message {
	mi := &file_framing_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RPCStreamHeader_Continue.ProtoReflect.Descriptor instead.
func (*RPCStreamHeader_Continue) Descriptor() ([]byte, []int) {
	return file_framing_proto_rawDescGZIP(), []int{3, 0}
}

var File_framing_proto protoreflect.FileDescriptor

var file_framing_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x66, 0x72, 0x61, 0x6d, 0x69, 0x6e, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x17, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e,
	0x70, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x22, 0x30, 0x0a, 0x10, 0x43, 0x6f, 0x6e, 0x6e,
	0x65, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1c, 0x0a, 0x09,
	0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x78, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x09, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x78, 0x22, 0x27, 0x0a, 0x09, 0x52, 0x50,
	0x43, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x22, 0xc7, 0x01, 0x0a, 0x09, 0x52, 0x50, 0x43, 0x46, 0x6f, 0x6f, 0x74, 0x65,
	0x72, 0x12, 0x46, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69,
	0x73, 0x6c, 0x65, 0x2e, 0x70, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x52, 0x50, 0x43,
	0x46, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x2e, 0x53, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x48, 0x00,
	0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x40, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c,
	0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x70, 0x62, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x2e, 0x52, 0x50, 0x43, 0x46, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0x09, 0x0a, 0x07, 0x53,
	0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x1a, 0x19, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0xb9, 0x01,
	0x0a, 0x0f, 0x52, 0x50, 0x43, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x4f, 0x0a, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x31, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e,
	0x69, 0x73, 0x6c, 0x65, 0x2e, 0x70, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x52, 0x50,
	0x43, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x2e, 0x43, 0x6f,
	0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x48, 0x00, 0x52, 0x08, 0x63, 0x6f, 0x6e, 0x74, 0x69, 0x6e,
	0x75, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x66, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69,
	0x73, 0x6c, 0x65, 0x2e, 0x70, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x2e, 0x52, 0x50, 0x43,
	0x46, 0x6f, 0x6f, 0x74, 0x65, 0x72, 0x48, 0x00, 0x52, 0x06, 0x66, 0x6f, 0x6f, 0x74, 0x65, 0x72,
	0x1a, 0x0a, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x74, 0x69, 0x6e, 0x75, 0x65, 0x42, 0x0b, 0x0a, 0x09,
	0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x1d, 0x5a, 0x1b, 0x6c, 0x61, 0x62,
	0x34, 0x37, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x69, 0x73, 0x6c, 0x65, 0x2f, 0x70, 0x6b, 0x67, 0x2f,
	0x70, 0x62, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_framing_proto_rawDescOnce sync.Once
	file_framing_proto_rawDescData = file_framing_proto_rawDesc
)

func file_framing_proto_rawDescGZIP() []byte {
	file_framing_proto_rawDescOnce.Do(func() {
		file_framing_proto_rawDescData = protoimpl.X.CompressGZIP(file_framing_proto_rawDescData)
	})
	return file_framing_proto_rawDescData
}

var file_framing_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_framing_proto_goTypes = []interface{}{
	(*ConnectionHeader)(nil),         // 0: dev.lab47.isle.pbstream.ConnectionHeader
	(*RPCHeader)(nil),                // 1: dev.lab47.isle.pbstream.RPCHeader
	(*RPCFooter)(nil),                // 2: dev.lab47.isle.pbstream.RPCFooter
	(*RPCStreamHeader)(nil),          // 3: dev.lab47.isle.pbstream.RPCStreamHeader
	(*RPCFooter_Success)(nil),        // 4: dev.lab47.isle.pbstream.RPCFooter.Success
	(*RPCFooter_Error)(nil),          // 5: dev.lab47.isle.pbstream.RPCFooter.Error
	(*RPCStreamHeader_Continue)(nil), // 6: dev.lab47.isle.pbstream.RPCStreamHeader.Continue
}
var file_framing_proto_depIdxs = []int32{
	4, // 0: dev.lab47.isle.pbstream.RPCFooter.success:type_name -> dev.lab47.isle.pbstream.RPCFooter.Success
	5, // 1: dev.lab47.isle.pbstream.RPCFooter.error:type_name -> dev.lab47.isle.pbstream.RPCFooter.Error
	6, // 2: dev.lab47.isle.pbstream.RPCStreamHeader.continue:type_name -> dev.lab47.isle.pbstream.RPCStreamHeader.Continue
	2, // 3: dev.lab47.isle.pbstream.RPCStreamHeader.footer:type_name -> dev.lab47.isle.pbstream.RPCFooter
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_framing_proto_init() }
func file_framing_proto_init() {
	if File_framing_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_framing_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConnectionHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framing_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framing_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCFooter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framing_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCStreamHeader); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framing_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCFooter_Success); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framing_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCFooter_Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_framing_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RPCStreamHeader_Continue); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_framing_proto_msgTypes[2].OneofWrappers = []interface{}{
		(*RPCFooter_Success_)(nil),
		(*RPCFooter_Error_)(nil),
	}
	file_framing_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*RPCStreamHeader_Continue_)(nil),
		(*RPCStreamHeader_Footer)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_framing_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_framing_proto_goTypes,
		DependencyIndexes: file_framing_proto_depIdxs,
		MessageInfos:      file_framing_proto_msgTypes,
	}.Build()
	File_framing_proto = out.File
	file_framing_proto_rawDesc = nil
	file_framing_proto_goTypes = nil
	file_framing_proto_depIdxs = nil
}
