// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: timesync.proto

package timesync

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NTPTimePacket struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	T1 int64 `protobuf:"varint,1,opt,name=t1,proto3" json:"t1,omitempty"`
	T2 int64 `protobuf:"varint,2,opt,name=t2,proto3" json:"t2,omitempty"`
	T3 int64 `protobuf:"varint,3,opt,name=t3,proto3" json:"t3,omitempty"`
	T4 int64 `protobuf:"varint,4,opt,name=t4,proto3" json:"t4,omitempty"`
}

func (x *NTPTimePacket) Reset() {
	*x = NTPTimePacket{}
	if protoimpl.UnsafeEnabled {
		mi := &file_timesync_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NTPTimePacket) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NTPTimePacket) ProtoMessage() {}

func (x *NTPTimePacket) ProtoReflect() protoreflect.Message {
	mi := &file_timesync_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NTPTimePacket.ProtoReflect.Descriptor instead.
func (*NTPTimePacket) Descriptor() ([]byte, []int) {
	return file_timesync_proto_rawDescGZIP(), []int{0}
}

func (x *NTPTimePacket) GetT1() int64 {
	if x != nil {
		return x.T1
	}
	return 0
}

func (x *NTPTimePacket) GetT2() int64 {
	if x != nil {
		return x.T2
	}
	return 0
}

func (x *NTPTimePacket) GetT3() int64 {
	if x != nil {
		return x.T3
	}
	return 0
}

func (x *NTPTimePacket) GetT4() int64 {
	if x != nil {
		return x.T4
	}
	return 0
}

var File_timesync_proto protoreflect.FileDescriptor

var file_timesync_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65,
	0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x22, 0x4f, 0x0a, 0x0d, 0x4e, 0x54, 0x50,
	0x54, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x31,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x31, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x32,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x32, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x33,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x33, 0x12, 0x0e, 0x0a, 0x02, 0x74, 0x34,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x74, 0x34, 0x32, 0x6c, 0x0a, 0x08, 0x54, 0x69,
	0x6d, 0x65, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x60, 0x0a, 0x08, 0x54, 0x69, 0x6d, 0x65, 0x53, 0x79,
	0x6e, 0x63, 0x12, 0x26, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69,
	0x73, 0x6c, 0x65, 0x2e, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x79, 0x6e, 0x63, 0x2e, 0x4e, 0x54, 0x50,
	0x54, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x1a, 0x26, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x79, 0x6e, 0x63, 0x2e, 0x4e, 0x54, 0x50, 0x54, 0x69, 0x6d, 0x65, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x22, 0x00, 0x28, 0x01, 0x30, 0x01, 0x42, 0x26, 0x5a, 0x24, 0x6c, 0x61, 0x62, 0x34,
	0x37, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x69, 0x73, 0x6c, 0x65, 0x2f, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x70, 0x69, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x79, 0x6e, 0x63,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_timesync_proto_rawDescOnce sync.Once
	file_timesync_proto_rawDescData = file_timesync_proto_rawDesc
)

func file_timesync_proto_rawDescGZIP() []byte {
	file_timesync_proto_rawDescOnce.Do(func() {
		file_timesync_proto_rawDescData = protoimpl.X.CompressGZIP(file_timesync_proto_rawDescData)
	})
	return file_timesync_proto_rawDescData
}

var file_timesync_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_timesync_proto_goTypes = []interface{}{
	(*NTPTimePacket)(nil), // 0: dev.lab47.isle.timesync.NTPTimePacket
}
var file_timesync_proto_depIdxs = []int32{
	0, // 0: dev.lab47.isle.timesync.TimeSync.TimeSync:input_type -> dev.lab47.isle.timesync.NTPTimePacket
	0, // 1: dev.lab47.isle.timesync.TimeSync.TimeSync:output_type -> dev.lab47.isle.timesync.NTPTimePacket
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_timesync_proto_init() }
func file_timesync_proto_init() {
	if File_timesync_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_timesync_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NTPTimePacket); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_timesync_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_timesync_proto_goTypes,
		DependencyIndexes: file_timesync_proto_depIdxs,
		MessageInfos:      file_timesync_proto_msgTypes,
	}.Build()
	File_timesync_proto = out.File
	file_timesync_proto_rawDesc = nil
	file_timesync_proto_goTypes = nil
	file_timesync_proto_depIdxs = nil
}
