// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: api.proto

package guestapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddAppReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Selector string `protobuf:"bytes,2,opt,name=selector,proto3" json:"selector,omitempty"`
}

func (x *AddAppReq) Reset() {
	*x = AddAppReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppReq) ProtoMessage() {}

func (x *AddAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppReq.ProtoReflect.Descriptor instead.
func (*AddAppReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{0}
}

func (x *AddAppReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AddAppReq) GetSelector() string {
	if x != nil {
		return x.Selector
	}
	return ""
}

type AddAppResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *AddAppResp) Reset() {
	*x = AddAppResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddAppResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAppResp) ProtoMessage() {}

func (x *AddAppResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAppResp.ProtoReflect.Descriptor instead.
func (*AddAppResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{1}
}

func (x *AddAppResp) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DisableAppReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DisableAppReq) Reset() {
	*x = DisableAppReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableAppReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAppReq) ProtoMessage() {}

func (x *DisableAppReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAppReq.ProtoReflect.Descriptor instead.
func (*DisableAppReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{2}
}

func (x *DisableAppReq) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DisableAppResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DisableAppResp) Reset() {
	*x = DisableAppResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DisableAppResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DisableAppResp) ProtoMessage() {}

func (x *DisableAppResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DisableAppResp.ProtoReflect.Descriptor instead.
func (*DisableAppResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{3}
}

type RunInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Command []string `protobuf:"bytes,1,rep,name=command,proto3" json:"command,omitempty"`
	Input   []byte   `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	Closed  bool     `protobuf:"varint,3,opt,name=closed,proto3" json:"closed,omitempty"`
}

func (x *RunInput) Reset() {
	*x = RunInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunInput) ProtoMessage() {}

func (x *RunInput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunInput.ProtoReflect.Descriptor instead.
func (*RunInput) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{4}
}

func (x *RunInput) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *RunInput) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunInput) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

type RunOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Data     []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	Closed   bool   `protobuf:"varint,2,opt,name=closed,proto3" json:"closed,omitempty"`
	ExitCode int32  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
}

func (x *RunOutput) Reset() {
	*x = RunOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOutput) ProtoMessage() {}

func (x *RunOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOutput.ProtoReflect.Descriptor instead.
func (*RunOutput) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{5}
}

func (x *RunOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *RunOutput) GetClosed() bool {
	if x != nil {
		return x.Closed
	}
	return false
}

func (x *RunOutput) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

type RunOnMacResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ExitCode int32  `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	Output   []byte `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"`
}

func (x *RunOnMacResp) Reset() {
	*x = RunOnMacResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunOnMacResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunOnMacResp) ProtoMessage() {}

func (x *RunOnMacResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunOnMacResp.ProtoReflect.Descriptor instead.
func (*RunOnMacResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{6}
}

func (x *RunOnMacResp) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunOnMacResp) GetOutput() []byte {
	if x != nil {
		return x.Output
	}
	return nil
}

type RunningReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ip string `protobuf:"bytes,1,opt,name=ip,proto3" json:"ip,omitempty"`
}

func (x *RunningReq) Reset() {
	*x = RunningReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunningReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningReq) ProtoMessage() {}

func (x *RunningReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningReq.ProtoReflect.Descriptor instead.
func (*RunningReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{7}
}

func (x *RunningReq) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

type RunningResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *RunningResp) Reset() {
	*x = RunningResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunningResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunningResp) ProtoMessage() {}

func (x *RunningResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunningResp.ProtoReflect.Descriptor instead.
func (*RunningResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{8}
}

type StartPortForwardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port int32  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *StartPortForwardReq) Reset() {
	*x = StartPortForwardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPortForwardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPortForwardReq) ProtoMessage() {}

func (x *StartPortForwardReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPortForwardReq.ProtoReflect.Descriptor instead.
func (*StartPortForwardReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{9}
}

func (x *StartPortForwardReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *StartPortForwardReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type StartPortForwardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *StartPortForwardResp) Reset() {
	*x = StartPortForwardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StartPortForwardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartPortForwardResp) ProtoMessage() {}

func (x *StartPortForwardResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartPortForwardResp.ProtoReflect.Descriptor instead.
func (*StartPortForwardResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{10}
}

type CancelPortForwardReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Port int32  `protobuf:"varint,1,opt,name=port,proto3" json:"port,omitempty"`
	Key  string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *CancelPortForwardReq) Reset() {
	*x = CancelPortForwardReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPortForwardReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPortForwardReq) ProtoMessage() {}

func (x *CancelPortForwardReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPortForwardReq.ProtoReflect.Descriptor instead.
func (*CancelPortForwardReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{11}
}

func (x *CancelPortForwardReq) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

func (x *CancelPortForwardReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type CancelPortForwardResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CancelPortForwardResp) Reset() {
	*x = CancelPortForwardResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CancelPortForwardResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelPortForwardResp) ProtoMessage() {}

func (x *CancelPortForwardResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelPortForwardResp.ProtoReflect.Descriptor instead.
func (*CancelPortForwardResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{12}
}

type TrimMemoryReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Set    int32 `protobuf:"varint,1,opt,name=set,proto3" json:"set,omitempty"`
	Adjust int32 `protobuf:"varint,2,opt,name=adjust,proto3" json:"adjust,omitempty"`
	Reset_ bool  `protobuf:"varint,3,opt,name=reset,proto3" json:"reset,omitempty"`
}

func (x *TrimMemoryReq) Reset() {
	*x = TrimMemoryReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrimMemoryReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimMemoryReq) ProtoMessage() {}

func (x *TrimMemoryReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimMemoryReq.ProtoReflect.Descriptor instead.
func (*TrimMemoryReq) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{13}
}

func (x *TrimMemoryReq) GetSet() int32 {
	if x != nil {
		return x.Set
	}
	return 0
}

func (x *TrimMemoryReq) GetAdjust() int32 {
	if x != nil {
		return x.Adjust
	}
	return 0
}

func (x *TrimMemoryReq) GetReset_() bool {
	if x != nil {
		return x.Reset_
	}
	return false
}

type TrimMemoryResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TotalMemory int32 `protobuf:"varint,1,opt,name=total_memory,json=totalMemory,proto3" json:"total_memory,omitempty"`
}

func (x *TrimMemoryResp) Reset() {
	*x = TrimMemoryResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TrimMemoryResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TrimMemoryResp) ProtoMessage() {}

func (x *TrimMemoryResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TrimMemoryResp.ProtoReflect.Descriptor instead.
func (*TrimMemoryResp) Descriptor() ([]byte, []int) {
	return file_api_proto_rawDescGZIP(), []int{14}
}

func (x *TrimMemoryResp) GetTotalMemory() int32 {
	if x != nil {
		return x.TotalMemory
	}
	return 0
}

var File_api_proto protoreflect.FileDescriptor

var file_api_proto_rawDesc = []byte{
	0x0a, 0x09, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17, 0x64, 0x65, 0x76,
	0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x22, 0x3b, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x71, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6c, 0x65, 0x63, 0x74, 0x6f,
	0x72, 0x22, 0x1c, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22,
	0x1f, 0x0a, 0x0d, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64,
	0x22, 0x10, 0x0a, 0x0e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65,
	0x73, 0x70, 0x22, 0x52, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x05, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x16,
	0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06,
	0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x22, 0x54, 0x0a, 0x09, 0x52, 0x75, 0x6e, 0x4f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x63, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x12,
	0x1b, 0x0a, 0x09, 0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x22, 0x43, 0x0a, 0x0c,
	0x52, 0x75, 0x6e, 0x4f, 0x6e, 0x4d, 0x61, 0x63, 0x52, 0x65, 0x73, 0x70, 0x12, 0x1b, 0x0a, 0x09,
	0x65, 0x78, 0x69, 0x74, 0x5f, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x08, 0x65, 0x78, 0x69, 0x74, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6f, 0x75, 0x74,
	0x70, 0x75, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x6f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x22, 0x1c, 0x0a, 0x0a, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x22,
	0x0d, 0x0a, 0x0b, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x73, 0x70, 0x22, 0x3b,
	0x0a, 0x13, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61,
	0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x22, 0x16, 0x0a, 0x14, 0x53,
	0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x3c, 0x0a, 0x14, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x6f, 0x72,
	0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12,
	0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65,
	0x79, 0x22, 0x17, 0x0a, 0x15, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x46,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x22, 0x4f, 0x0a, 0x0d, 0x54, 0x72,
	0x69, 0x6d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x12, 0x10, 0x0a, 0x03, 0x73,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x73, 0x65, 0x74, 0x12, 0x16, 0x0a,
	0x06, 0x61, 0x64, 0x6a, 0x75, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61,
	0x64, 0x6a, 0x75, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x72, 0x65, 0x73, 0x65, 0x74, 0x22, 0x33, 0x0a, 0x0e, 0x54,
	0x72, 0x69, 0x6d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x12, 0x21, 0x0a,
	0x0c, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x32, 0xc8, 0x03, 0x0a, 0x08, 0x47, 0x75, 0x65, 0x73, 0x74, 0x41, 0x50, 0x49, 0x12, 0x51, 0x0a,
	0x06, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x12, 0x22, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61,
	0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70,
	0x69, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x23, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x41, 0x64, 0x64, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x5d, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x12, 0x26,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65,
	0x41, 0x70, 0x70, 0x52, 0x65, 0x71, 0x1a, 0x27, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62,
	0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69,
	0x2e, 0x44, 0x69, 0x73, 0x61, 0x62, 0x6c, 0x65, 0x41, 0x70, 0x70, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x55, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x4f, 0x6e, 0x4d, 0x61, 0x63, 0x12, 0x21, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x75, 0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x22,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x75, 0x6e, 0x4f, 0x75, 0x74, 0x70,
	0x75, 0x74, 0x28, 0x01, 0x30, 0x01, 0x12, 0x54, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x73, 0x6f, 0x6c,
	0x65, 0x12, 0x21, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73,
	0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x75, 0x6e, 0x49,
	0x6e, 0x70, 0x75, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37,
	0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x75, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x28, 0x01, 0x30, 0x01, 0x12, 0x5d, 0x0a, 0x0a,
	0x54, 0x72, 0x69, 0x6d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x26, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x69, 0x6d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x1a, 0x27, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69,
	0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x69,
	0x6d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x32, 0xfa, 0x03, 0x0a, 0x07,
	0x48, 0x6f, 0x73, 0x74, 0x41, 0x50, 0x49, 0x12, 0x55, 0x0a, 0x08, 0x52, 0x75, 0x6e, 0x4f, 0x6e,
	0x4d, 0x61, 0x63, 0x12, 0x21, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e,
	0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x75,
	0x6e, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x22, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62,
	0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x75, 0x6e, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x28, 0x01, 0x30, 0x01, 0x12, 0x54,
	0x0a, 0x07, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x12, 0x23, 0x2e, 0x64, 0x65, 0x76, 0x2e,
	0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67, 0x52, 0x65, 0x71, 0x1a, 0x24,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x75, 0x6e, 0x6e, 0x69, 0x6e, 0x67,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x6f, 0x0a, 0x10, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x72,
	0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x2c, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c,
	0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x70, 0x69, 0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77,
	0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x2d, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62,
	0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69,
	0x2e, 0x53, 0x74, 0x61, 0x72, 0x74, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72,
	0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x72, 0x0a, 0x11, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50,
	0x6f, 0x72, 0x74, 0x46, 0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x12, 0x2d, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x46,
	0x6f, 0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x2e, 0x2e, 0x64, 0x65, 0x76, 0x2e,
	0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x50, 0x6f, 0x72, 0x74, 0x46, 0x6f,
	0x72, 0x77, 0x61, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5d, 0x0a, 0x0a, 0x54, 0x72, 0x69,
	0x6d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x12, 0x26, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61,
	0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70,
	0x69, 0x2e, 0x54, 0x72, 0x69, 0x6d, 0x4d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x71, 0x1a,
	0x27, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65,
	0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x54, 0x72, 0x69, 0x6d, 0x4d, 0x65,
	0x6d, 0x6f, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x42, 0x19, 0x5a, 0x17, 0x6c, 0x61, 0x62, 0x34,
	0x37, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x69, 0x73, 0x6c, 0x65, 0x2f, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_proto_rawDescOnce sync.Once
	file_api_proto_rawDescData = file_api_proto_rawDesc
)

func file_api_proto_rawDescGZIP() []byte {
	file_api_proto_rawDescOnce.Do(func() {
		file_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_proto_rawDescData)
	})
	return file_api_proto_rawDescData
}

var file_api_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_goTypes = []interface{}{
	(*AddAppReq)(nil),             // 0: dev.lab47.isle.guestapi.AddAppReq
	(*AddAppResp)(nil),            // 1: dev.lab47.isle.guestapi.AddAppResp
	(*DisableAppReq)(nil),         // 2: dev.lab47.isle.guestapi.DisableAppReq
	(*DisableAppResp)(nil),        // 3: dev.lab47.isle.guestapi.DisableAppResp
	(*RunInput)(nil),              // 4: dev.lab47.isle.guestapi.RunInput
	(*RunOutput)(nil),             // 5: dev.lab47.isle.guestapi.RunOutput
	(*RunOnMacResp)(nil),          // 6: dev.lab47.isle.guestapi.RunOnMacResp
	(*RunningReq)(nil),            // 7: dev.lab47.isle.guestapi.RunningReq
	(*RunningResp)(nil),           // 8: dev.lab47.isle.guestapi.RunningResp
	(*StartPortForwardReq)(nil),   // 9: dev.lab47.isle.guestapi.StartPortForwardReq
	(*StartPortForwardResp)(nil),  // 10: dev.lab47.isle.guestapi.StartPortForwardResp
	(*CancelPortForwardReq)(nil),  // 11: dev.lab47.isle.guestapi.CancelPortForwardReq
	(*CancelPortForwardResp)(nil), // 12: dev.lab47.isle.guestapi.CancelPortForwardResp
	(*TrimMemoryReq)(nil),         // 13: dev.lab47.isle.guestapi.TrimMemoryReq
	(*TrimMemoryResp)(nil),        // 14: dev.lab47.isle.guestapi.TrimMemoryResp
}
var file_api_proto_depIdxs = []int32{
	0,  // 0: dev.lab47.isle.guestapi.GuestAPI.AddApp:input_type -> dev.lab47.isle.guestapi.AddAppReq
	2,  // 1: dev.lab47.isle.guestapi.GuestAPI.DisableApp:input_type -> dev.lab47.isle.guestapi.DisableAppReq
	4,  // 2: dev.lab47.isle.guestapi.GuestAPI.RunOnMac:input_type -> dev.lab47.isle.guestapi.RunInput
	4,  // 3: dev.lab47.isle.guestapi.GuestAPI.Console:input_type -> dev.lab47.isle.guestapi.RunInput
	13, // 4: dev.lab47.isle.guestapi.GuestAPI.TrimMemory:input_type -> dev.lab47.isle.guestapi.TrimMemoryReq
	4,  // 5: dev.lab47.isle.guestapi.HostAPI.RunOnMac:input_type -> dev.lab47.isle.guestapi.RunInput
	7,  // 6: dev.lab47.isle.guestapi.HostAPI.Running:input_type -> dev.lab47.isle.guestapi.RunningReq
	9,  // 7: dev.lab47.isle.guestapi.HostAPI.StartPortForward:input_type -> dev.lab47.isle.guestapi.StartPortForwardReq
	11, // 8: dev.lab47.isle.guestapi.HostAPI.CancelPortForward:input_type -> dev.lab47.isle.guestapi.CancelPortForwardReq
	13, // 9: dev.lab47.isle.guestapi.HostAPI.TrimMemory:input_type -> dev.lab47.isle.guestapi.TrimMemoryReq
	1,  // 10: dev.lab47.isle.guestapi.GuestAPI.AddApp:output_type -> dev.lab47.isle.guestapi.AddAppResp
	3,  // 11: dev.lab47.isle.guestapi.GuestAPI.DisableApp:output_type -> dev.lab47.isle.guestapi.DisableAppResp
	5,  // 12: dev.lab47.isle.guestapi.GuestAPI.RunOnMac:output_type -> dev.lab47.isle.guestapi.RunOutput
	5,  // 13: dev.lab47.isle.guestapi.GuestAPI.Console:output_type -> dev.lab47.isle.guestapi.RunOutput
	14, // 14: dev.lab47.isle.guestapi.GuestAPI.TrimMemory:output_type -> dev.lab47.isle.guestapi.TrimMemoryResp
	5,  // 15: dev.lab47.isle.guestapi.HostAPI.RunOnMac:output_type -> dev.lab47.isle.guestapi.RunOutput
	8,  // 16: dev.lab47.isle.guestapi.HostAPI.Running:output_type -> dev.lab47.isle.guestapi.RunningResp
	10, // 17: dev.lab47.isle.guestapi.HostAPI.StartPortForward:output_type -> dev.lab47.isle.guestapi.StartPortForwardResp
	12, // 18: dev.lab47.isle.guestapi.HostAPI.CancelPortForward:output_type -> dev.lab47.isle.guestapi.CancelPortForwardResp
	14, // 19: dev.lab47.isle.guestapi.HostAPI.TrimMemory:output_type -> dev.lab47.isle.guestapi.TrimMemoryResp
	10, // [10:20] is the sub-list for method output_type
	0,  // [0:10] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_init() }
func file_api_proto_init() {
	if File_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAppReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddAppResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableAppReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DisableAppResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunOnMacResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunningReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RunningResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPortForwardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StartPortForwardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPortForwardReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CancelPortForwardResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrimMemoryReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TrimMemoryResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_api_proto_goTypes,
		DependencyIndexes: file_api_proto_depIdxs,
		MessageInfos:      file_api_proto_msgTypes,
	}.Build()
	File_api_proto = out.File
	file_api_proto_rawDesc = nil
	file_api_proto_goTypes = nil
	file_api_proto_depIdxs = nil
}
