// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: labels.proto

package guestapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Labels struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pairs []*Labels_Pair `protobuf:"bytes,1,rep,name=pairs,proto3" json:"pairs,omitempty"`
}

func (x *Labels) Reset() {
	*x = Labels{}
	if protoimpl.UnsafeEnabled {
		mi := &file_labels_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Labels) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels) ProtoMessage() {}

func (x *Labels) ProtoReflect() protoreflect.Message {
	mi := &file_labels_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels.ProtoReflect.Descriptor instead.
func (*Labels) Descriptor() ([]byte, []int) {
	return file_labels_proto_rawDescGZIP(), []int{0}
}

func (x *Labels) GetPairs() []*Labels_Pair {
	if x != nil {
		return x.Pairs
	}
	return nil
}

type Labels_Pair struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Labels_Pair) Reset() {
	*x = Labels_Pair{}
	if protoimpl.UnsafeEnabled {
		mi := &file_labels_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Labels_Pair) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Labels_Pair) ProtoMessage() {}

func (x *Labels_Pair) ProtoReflect() protoreflect.Message {
	mi := &file_labels_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Labels_Pair.ProtoReflect.Descriptor instead.
func (*Labels_Pair) Descriptor() ([]byte, []int) {
	return file_labels_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Labels_Pair) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *Labels_Pair) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_labels_proto protoreflect.FileDescriptor

var file_labels_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x6c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x17,
	0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x22, 0x74, 0x0a, 0x06, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x12, 0x3a, 0x0a, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x24, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c,
	0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x4c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x52, 0x05, 0x70, 0x61, 0x69, 0x72, 0x73, 0x1a, 0x2e, 0x0a,
	0x04, 0x50, 0x61, 0x69, 0x72, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x19, 0x5a,
	0x17, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x69, 0x73, 0x6c, 0x65, 0x2f,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_labels_proto_rawDescOnce sync.Once
	file_labels_proto_rawDescData = file_labels_proto_rawDesc
)

func file_labels_proto_rawDescGZIP() []byte {
	file_labels_proto_rawDescOnce.Do(func() {
		file_labels_proto_rawDescData = protoimpl.X.CompressGZIP(file_labels_proto_rawDescData)
	})
	return file_labels_proto_rawDescData
}

var file_labels_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_labels_proto_goTypes = []interface{}{
	(*Labels)(nil),      // 0: dev.lab47.isle.guestapi.Labels
	(*Labels_Pair)(nil), // 1: dev.lab47.isle.guestapi.Labels.Pair
}
var file_labels_proto_depIdxs = []int32{
	1, // 0: dev.lab47.isle.guestapi.Labels.pairs:type_name -> dev.lab47.isle.guestapi.Labels.Pair
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_labels_proto_init() }
func file_labels_proto_init() {
	if File_labels_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_labels_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Labels); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_labels_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Labels_Pair); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_labels_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_labels_proto_goTypes,
		DependencyIndexes: file_labels_proto_depIdxs,
		MessageInfos:      file_labels_proto_msgTypes,
	}.Build()
	File_labels_proto = out.File
	file_labels_proto_rawDesc = nil
	file_labels_proto_goTypes = nil
	file_labels_proto_depIdxs = nil
}
