// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: postgres.proto

package guestapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostgresServer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name    string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version string `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *PostgresServer) Reset() {
	*x = PostgresServer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostgresServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresServer) ProtoMessage() {}

func (x *PostgresServer) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresServer.ProtoReflect.Descriptor instead.
func (*PostgresServer) Descriptor() ([]byte, []int) {
	return file_postgres_proto_rawDescGZIP(), []int{0}
}

func (x *PostgresServer) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostgresServer) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PostgresDatabase struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Server   string `protobuf:"bytes,1,opt,name=server,proto3" json:"server,omitempty"`
	Name     string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	User     string `protobuf:"bytes,3,opt,name=user,proto3" json:"user,omitempty"`
	Password string `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
}

func (x *PostgresDatabase) Reset() {
	*x = PostgresDatabase{}
	if protoimpl.UnsafeEnabled {
		mi := &file_postgres_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostgresDatabase) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostgresDatabase) ProtoMessage() {}

func (x *PostgresDatabase) ProtoReflect() protoreflect.Message {
	mi := &file_postgres_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostgresDatabase.ProtoReflect.Descriptor instead.
func (*PostgresDatabase) Descriptor() ([]byte, []int) {
	return file_postgres_proto_rawDescGZIP(), []int{1}
}

func (x *PostgresDatabase) GetServer() string {
	if x != nil {
		return x.Server
	}
	return ""
}

func (x *PostgresDatabase) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostgresDatabase) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *PostgresDatabase) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

var File_postgres_proto protoreflect.FileDescriptor

var file_postgres_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x70, 0x6f, 0x73, 0x74, 0x67, 0x72, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65,
	0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x22, 0x3e, 0x0a, 0x0e, 0x50, 0x6f, 0x73,
	0x74, 0x67, 0x72, 0x65, 0x73, 0x53, 0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x6e, 0x0a, 0x10, 0x50, 0x6f, 0x73,
	0x74, 0x67, 0x72, 0x65, 0x73, 0x44, 0x61, 0x74, 0x61, 0x62, 0x61, 0x73, 0x65, 0x12, 0x16, 0x0a,
	0x06, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x1a, 0x0a,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x42, 0x19, 0x5a, 0x17, 0x6c, 0x61, 0x62,
	0x34, 0x37, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x69, 0x73, 0x6c, 0x65, 0x2f, 0x67, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_postgres_proto_rawDescOnce sync.Once
	file_postgres_proto_rawDescData = file_postgres_proto_rawDesc
)

func file_postgres_proto_rawDescGZIP() []byte {
	file_postgres_proto_rawDescOnce.Do(func() {
		file_postgres_proto_rawDescData = protoimpl.X.CompressGZIP(file_postgres_proto_rawDescData)
	})
	return file_postgres_proto_rawDescData
}

var file_postgres_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_postgres_proto_goTypes = []interface{}{
	(*PostgresServer)(nil),   // 0: dev.lab47.isle.guestapi.PostgresServer
	(*PostgresDatabase)(nil), // 1: dev.lab47.isle.guestapi.PostgresDatabase
}
var file_postgres_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_postgres_proto_init() }
func file_postgres_proto_init() {
	if File_postgres_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_postgres_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostgresServer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_postgres_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostgresDatabase); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_postgres_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_postgres_proto_goTypes,
		DependencyIndexes: file_postgres_proto_depIdxs,
		MessageInfos:      file_postgres_proto_msgTypes,
	}.Build()
	File_postgres_proto = out.File
	file_postgres_proto_rawDesc = nil
	file_postgres_proto_goTypes = nil
	file_postgres_proto_depIdxs = nil
}
