// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.6.1
// source: resources.proto

package guestapi

import (
	any1 "github.com/golang/protobuf/ptypes/any"
	_struct "github.com/golang/protobuf/ptypes/struct"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ProvisionStatus_Status int32

const (
	ProvisionStatus_UNKNOWN   ProvisionStatus_Status = 0
	ProvisionStatus_ADDING    ProvisionStatus_Status = 1
	ProvisionStatus_RUNNING   ProvisionStatus_Status = 2
	ProvisionStatus_SUSPENDED ProvisionStatus_Status = 3
	ProvisionStatus_DEAD      ProvisionStatus_Status = 4
)

// Enum value maps for ProvisionStatus_Status.
var (
	ProvisionStatus_Status_name = map[int32]string{
		0: "UNKNOWN",
		1: "ADDING",
		2: "RUNNING",
		3: "SUSPENDED",
		4: "DEAD",
	}
	ProvisionStatus_Status_value = map[string]int32{
		"UNKNOWN":   0,
		"ADDING":    1,
		"RUNNING":   2,
		"SUSPENDED": 3,
		"DEAD":      4,
	}
)

func (x ProvisionStatus_Status) Enum() *ProvisionStatus_Status {
	p := new(ProvisionStatus_Status)
	*p = x
	return p
}

func (x ProvisionStatus_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProvisionStatus_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_resources_proto_enumTypes[0].Descriptor()
}

func (ProvisionStatus_Status) Type() protoreflect.EnumType {
	return &file_resources_proto_enumTypes[0]
}

func (x ProvisionStatus_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProvisionStatus_Status.Descriptor instead.
func (ProvisionStatus_Status) EnumDescriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{3, 0}
}

type IPAddress struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Mask    int32  `protobuf:"varint,2,opt,name=mask,proto3" json:"mask,omitempty"`
}

func (x *IPAddress) Reset() {
	*x = IPAddress{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IPAddress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IPAddress) ProtoMessage() {}

func (x *IPAddress) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IPAddress.ProtoReflect.Descriptor instead.
func (*IPAddress) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{0}
}

func (x *IPAddress) GetAddress() []byte {
	if x != nil {
		return x.Address
	}
	return nil
}

func (x *IPAddress) GetMask() int32 {
	if x != nil {
		return x.Mask
	}
	return 0
}

type NetworkInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Addresses []*IPAddress `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses,omitempty"`
	Ports     []int32      `protobuf:"varint,2,rep,packed,name=ports,proto3" json:"ports,omitempty"`
}

func (x *NetworkInfo) Reset() {
	*x = NetworkInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkInfo) ProtoMessage() {}

func (x *NetworkInfo) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkInfo.ProtoReflect.Descriptor instead.
func (*NetworkInfo) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{1}
}

func (x *NetworkInfo) GetAddresses() []*IPAddress {
	if x != nil {
		return x.Addresses
	}
	return nil
}

func (x *NetworkInfo) GetPorts() []int32 {
	if x != nil {
		return x.Ports
	}
	return nil
}

type ContainerInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	InitPid   int32                `protobuf:"varint,2,opt,name=init_pid,json=initPid,proto3" json:"init_pid,omitempty"`
	NodeId    string               `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Image     string               `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	Command   []string             `protobuf:"bytes,5,rep,name=command,proto3" json:"command,omitempty"`
	StartedAt *timestamp.Timestamp `protobuf:"bytes,6,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
}

func (x *ContainerInfo) Reset() {
	*x = ContainerInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ContainerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ContainerInfo) ProtoMessage() {}

func (x *ContainerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ContainerInfo.ProtoReflect.Descriptor instead.
func (*ContainerInfo) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{2}
}

func (x *ContainerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ContainerInfo) GetInitPid() int32 {
	if x != nil {
		return x.InitPid
	}
	return 0
}

func (x *ContainerInfo) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *ContainerInfo) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *ContainerInfo) GetCommand() []string {
	if x != nil {
		return x.Command
	}
	return nil
}

func (x *ContainerInfo) GetStartedAt() *timestamp.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

type ProvisionStatus struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status        ProvisionStatus_Status `protobuf:"varint,1,opt,name=status,proto3,enum=dev.lab47.isle.guestapi.ProvisionStatus_Status" json:"status,omitempty"`
	NetworkInfo   *NetworkInfo           `protobuf:"bytes,2,opt,name=network_info,json=networkInfo,proto3" json:"network_info,omitempty"`
	ContainerInfo *ContainerInfo         `protobuf:"bytes,3,opt,name=container_info,json=containerInfo,proto3" json:"container_info,omitempty"`
	LastError     string                 `protobuf:"bytes,4,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
}

func (x *ProvisionStatus) Reset() {
	*x = ProvisionStatus{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ProvisionStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ProvisionStatus) ProtoMessage() {}

func (x *ProvisionStatus) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ProvisionStatus.ProtoReflect.Descriptor instead.
func (*ProvisionStatus) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{3}
}

func (x *ProvisionStatus) GetStatus() ProvisionStatus_Status {
	if x != nil {
		return x.Status
	}
	return ProvisionStatus_UNKNOWN
}

func (x *ProvisionStatus) GetNetworkInfo() *NetworkInfo {
	if x != nil {
		return x.NetworkInfo
	}
	return nil
}

func (x *ProvisionStatus) GetContainerInfo() *ContainerInfo {
	if x != nil {
		return x.ContainerInfo
	}
	return nil
}

func (x *ProvisionStatus) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

type ResourceId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Type     string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	UniqueId []byte `protobuf:"bytes,3,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
}

func (x *ResourceId) Reset() {
	*x = ResourceId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceId) ProtoMessage() {}

func (x *ResourceId) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceId.ProtoReflect.Descriptor instead.
func (*ResourceId) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{4}
}

func (x *ResourceId) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ResourceId) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceId) GetUniqueId() []byte {
	if x != nil {
		return x.UniqueId
	}
	return nil
}

type ResourceIndexKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Category string         `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	Type     string         `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Field    int32          `protobuf:"varint,3,opt,name=field,proto3" json:"field,omitempty"`
	Value    *_struct.Value `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	UniqueId []byte         `protobuf:"bytes,5,opt,name=unique_id,json=uniqueId,proto3" json:"unique_id,omitempty"`
}

func (x *ResourceIndexKey) Reset() {
	*x = ResourceIndexKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceIndexKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceIndexKey) ProtoMessage() {}

func (x *ResourceIndexKey) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResourceIndexKey.ProtoReflect.Descriptor instead.
func (*ResourceIndexKey) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{5}
}

func (x *ResourceIndexKey) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ResourceIndexKey) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *ResourceIndexKey) GetField() int32 {
	if x != nil {
		return x.Field
	}
	return 0
}

func (x *ResourceIndexKey) GetValue() *_struct.Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *ResourceIndexKey) GetUniqueId() []byte {
	if x != nil {
		return x.UniqueId
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id              *ResourceId      `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Resource        *any1.Any        `protobuf:"bytes,2,opt,name=resource,proto3" json:"resource,omitempty"`
	ProvisionStatus *ProvisionStatus `protobuf:"bytes,3,opt,name=provision_status,json=provisionStatus,proto3" json:"provision_status,omitempty"`
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{6}
}

func (x *Resource) GetId() *ResourceId {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Resource) GetResource() *any1.Any {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *Resource) GetProvisionStatus() *ProvisionStatus {
	if x != nil {
		return x.ProvisionStatus
	}
	return nil
}

type CreateResourceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *any1.Any `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *CreateResourceReq) Reset() {
	*x = CreateResourceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceReq) ProtoMessage() {}

func (x *CreateResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceReq.ProtoReflect.Descriptor instead.
func (*CreateResourceReq) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{7}
}

func (x *CreateResourceReq) GetResource() *any1.Any {
	if x != nil {
		return x.Resource
	}
	return nil
}

type CreateResourceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *CreateResourceResp) Reset() {
	*x = CreateResourceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateResourceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResourceResp) ProtoMessage() {}

func (x *CreateResourceResp) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResourceResp.ProtoReflect.Descriptor instead.
func (*CreateResourceResp) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{8}
}

func (x *CreateResourceResp) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type UpdateResourceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *UpdateResourceReq) Reset() {
	*x = UpdateResourceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceReq) ProtoMessage() {}

func (x *UpdateResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceReq.ProtoReflect.Descriptor instead.
func (*UpdateResourceReq) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateResourceReq) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type UpdateResourceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *UpdateResourceResp) Reset() {
	*x = UpdateResourceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateResourceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResourceResp) ProtoMessage() {}

func (x *UpdateResourceResp) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResourceResp.ProtoReflect.Descriptor instead.
func (*UpdateResourceResp) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateResourceResp) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type ReadResourceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ResourceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ReadResourceReq) Reset() {
	*x = ReadResourceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceReq) ProtoMessage() {}

func (x *ReadResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceReq.ProtoReflect.Descriptor instead.
func (*ReadResourceReq) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{11}
}

func (x *ReadResourceReq) GetId() *ResourceId {
	if x != nil {
		return x.Id
	}
	return nil
}

type ReadResourceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *ReadResourceResp) Reset() {
	*x = ReadResourceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReadResourceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadResourceResp) ProtoMessage() {}

func (x *ReadResourceResp) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadResourceResp.ProtoReflect.Descriptor instead.
func (*ReadResourceResp) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{12}
}

func (x *ReadResourceResp) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

type CheckProvisionReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ResourceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CheckProvisionReq) Reset() {
	*x = CheckProvisionReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckProvisionReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProvisionReq) ProtoMessage() {}

func (x *CheckProvisionReq) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProvisionReq.ProtoReflect.Descriptor instead.
func (*CheckProvisionReq) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{13}
}

func (x *CheckProvisionReq) GetId() *ResourceId {
	if x != nil {
		return x.Id
	}
	return nil
}

type CheckProvisionResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status *ProvisionStatus `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *CheckProvisionResp) Reset() {
	*x = CheckProvisionResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckProvisionResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckProvisionResp) ProtoMessage() {}

func (x *CheckProvisionResp) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckProvisionResp.ProtoReflect.Descriptor instead.
func (*CheckProvisionResp) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{14}
}

func (x *CheckProvisionResp) GetStatus() *ProvisionStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type DeleteResourceReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id *ResourceId `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *DeleteResourceReq) Reset() {
	*x = DeleteResourceReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResourceReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceReq) ProtoMessage() {}

func (x *DeleteResourceReq) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceReq.ProtoReflect.Descriptor instead.
func (*DeleteResourceReq) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{15}
}

func (x *DeleteResourceReq) GetId() *ResourceId {
	if x != nil {
		return x.Id
	}
	return nil
}

type DeleteResourceResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Resource *Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
}

func (x *DeleteResourceResp) Reset() {
	*x = DeleteResourceResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_resources_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteResourceResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteResourceResp) ProtoMessage() {}

func (x *DeleteResourceResp) ProtoReflect() protoreflect.Message {
	mi := &file_resources_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteResourceResp.ProtoReflect.Descriptor instead.
func (*DeleteResourceResp) Descriptor() ([]byte, []int) {
	return file_resources_proto_rawDescGZIP(), []int{16}
}

func (x *DeleteResourceResp) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

var File_resources_proto protoreflect.FileDescriptor

var file_resources_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x17, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c,
	0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x1a, 0x19, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x6e, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x09, 0x49, 0x50, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6d,
	0x61, 0x73, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x6d, 0x61, 0x73, 0x6b, 0x22,
	0x65, 0x0a, 0x0b, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x40,
	0x0a, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x22, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73,
	0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x49, 0x50, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x09, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x65, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x05, 0x52,
	0x05, 0x70, 0x6f, 0x72, 0x74, 0x73, 0x22, 0xbe, 0x01, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x74, 0x61,
	0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x6e, 0x69, 0x74,
	0x5f, 0x70, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x69, 0x6e, 0x69, 0x74,
	0x50, 0x69, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05,
	0x69, 0x6d, 0x61, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x69, 0x6d, 0x61,
	0x67, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x18, 0x05, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6d, 0x6d, 0x61, 0x6e, 0x64, 0x12, 0x39, 0x0a, 0x0a,
	0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x22, 0xda, 0x02, 0x0a, 0x0f, 0x50, 0x72, 0x6f, 0x76,
	0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x47, 0x0a, 0x06, 0x73,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x2f, 0x2e, 0x64, 0x65,
	0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65,
	0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x2e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x12, 0x47, 0x0a, 0x0c, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x24, 0x2e, 0x64, 0x65, 0x76,
	0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73,
	0x74, 0x61, 0x70, 0x69, 0x2e, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x0b, 0x6e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x4d, 0x0a,
	0x0e, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x26, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34,
	0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x63,
	0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1d, 0x0a, 0x0a,
	0x6c, 0x61, 0x73, 0x74, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x6c, 0x61, 0x73, 0x74, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x06, 0x53,
	0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x41, 0x44, 0x44, 0x49, 0x4e, 0x47, 0x10, 0x01, 0x12, 0x0b,
	0x0a, 0x07, 0x52, 0x55, 0x4e, 0x4e, 0x49, 0x4e, 0x47, 0x10, 0x02, 0x12, 0x0d, 0x0a, 0x09, 0x53,
	0x55, 0x53, 0x50, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x03, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x45,
	0x41, 0x44, 0x10, 0x04, 0x22, 0x59, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79,
	0x70, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x5f, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x6e, 0x69, 0x71, 0x75, 0x65, 0x49, 0x64, 0x22,
	0xa3, 0x01, 0x0a, 0x10, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x4b, 0x65, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x74, 0x79, 0x70, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x05, 0x66, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x2c, 0x0a, 0x05, 0x76, 0x61,
	0x6c, 0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x75, 0x6e, 0x69, 0x71,
	0x75, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x75, 0x6e, 0x69,
	0x71, 0x75, 0x65, 0x49, 0x64, 0x22, 0xc6, 0x01, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x12, 0x33, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52,
	0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x70, 0x72, 0x6f,
	0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x28, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e,
	0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72,
	0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x0f, 0x70,
	0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x45,
	0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x12, 0x30, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x41, 0x6e, 0x79, 0x52, 0x08, 0x72, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x53, 0x0a, 0x12, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x08, 0x72,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e,
	0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x52, 0x0a, 0x11, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12,
	0x3d, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73,
	0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x53,
	0x0a, 0x12, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x3d, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62,
	0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69,
	0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x22, 0x46, 0x0a, 0x0f, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x23, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69,
	0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x51, 0x0a, 0x10, 0x52,
	0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x12,
	0x3d, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x21, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73,
	0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x22, 0x48,
	0x0a, 0x11, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e,
	0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x23, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65,
	0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x56, 0x0a, 0x12, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x40,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x28,
	0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e,
	0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69,
	0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0x48, 0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x12, 0x33, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x23, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73,
	0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x49, 0x64, 0x52, 0x02, 0x69, 0x64, 0x22, 0x53, 0x0a, 0x12, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x12, 0x3d, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x21, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69,
	0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x08, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x32,
	0xfe, 0x03, 0x0a, 0x0b, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x41, 0x50, 0x49, 0x12,
	0x61, 0x0a, 0x06, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e,
	0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74,
	0x61, 0x70, 0x69, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34,
	0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x61, 0x0a, 0x06, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x64,
	0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75,
	0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c,
	0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61,
	0x70, 0x69, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x12, 0x5b, 0x0a, 0x04, 0x52, 0x65, 0x61, 0x64, 0x12, 0x28, 0x2e,
	0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67,
	0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x71, 0x1a, 0x29, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61,
	0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70,
	0x69, 0x2e, 0x52, 0x65, 0x61, 0x64, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x69, 0x0a, 0x0e, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37,
	0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x43,
	0x68, 0x65, 0x63, 0x6b, 0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71,
	0x1a, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c,
	0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x50, 0x72, 0x6f, 0x76, 0x69, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x12, 0x61, 0x0a,
	0x06, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x2a, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61,
	0x62, 0x34, 0x37, 0x2e, 0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70,
	0x69, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65,
	0x52, 0x65, 0x71, 0x1a, 0x2b, 0x2e, 0x64, 0x65, 0x76, 0x2e, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e,
	0x69, 0x73, 0x6c, 0x65, 0x2e, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x42, 0x19, 0x5a, 0x17, 0x6c, 0x61, 0x62, 0x34, 0x37, 0x2e, 0x64, 0x65, 0x76, 0x2f, 0x69, 0x73,
	0x6c, 0x65, 0x2f, 0x67, 0x75, 0x65, 0x73, 0x74, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_resources_proto_rawDescOnce sync.Once
	file_resources_proto_rawDescData = file_resources_proto_rawDesc
)

func file_resources_proto_rawDescGZIP() []byte {
	file_resources_proto_rawDescOnce.Do(func() {
		file_resources_proto_rawDescData = protoimpl.X.CompressGZIP(file_resources_proto_rawDescData)
	})
	return file_resources_proto_rawDescData
}

var file_resources_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_resources_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_resources_proto_goTypes = []interface{}{
	(ProvisionStatus_Status)(0), // 0: dev.lab47.isle.guestapi.ProvisionStatus.Status
	(*IPAddress)(nil),           // 1: dev.lab47.isle.guestapi.IPAddress
	(*NetworkInfo)(nil),         // 2: dev.lab47.isle.guestapi.NetworkInfo
	(*ContainerInfo)(nil),       // 3: dev.lab47.isle.guestapi.ContainerInfo
	(*ProvisionStatus)(nil),     // 4: dev.lab47.isle.guestapi.ProvisionStatus
	(*ResourceId)(nil),          // 5: dev.lab47.isle.guestapi.ResourceId
	(*ResourceIndexKey)(nil),    // 6: dev.lab47.isle.guestapi.ResourceIndexKey
	(*Resource)(nil),            // 7: dev.lab47.isle.guestapi.Resource
	(*CreateResourceReq)(nil),   // 8: dev.lab47.isle.guestapi.CreateResourceReq
	(*CreateResourceResp)(nil),  // 9: dev.lab47.isle.guestapi.CreateResourceResp
	(*UpdateResourceReq)(nil),   // 10: dev.lab47.isle.guestapi.UpdateResourceReq
	(*UpdateResourceResp)(nil),  // 11: dev.lab47.isle.guestapi.UpdateResourceResp
	(*ReadResourceReq)(nil),     // 12: dev.lab47.isle.guestapi.ReadResourceReq
	(*ReadResourceResp)(nil),    // 13: dev.lab47.isle.guestapi.ReadResourceResp
	(*CheckProvisionReq)(nil),   // 14: dev.lab47.isle.guestapi.CheckProvisionReq
	(*CheckProvisionResp)(nil),  // 15: dev.lab47.isle.guestapi.CheckProvisionResp
	(*DeleteResourceReq)(nil),   // 16: dev.lab47.isle.guestapi.DeleteResourceReq
	(*DeleteResourceResp)(nil),  // 17: dev.lab47.isle.guestapi.DeleteResourceResp
	(*timestamp.Timestamp)(nil), // 18: google.protobuf.Timestamp
	(*_struct.Value)(nil),       // 19: google.protobuf.Value
	(*any1.Any)(nil),            // 20: google.protobuf.Any
}
var file_resources_proto_depIdxs = []int32{
	1,  // 0: dev.lab47.isle.guestapi.NetworkInfo.addresses:type_name -> dev.lab47.isle.guestapi.IPAddress
	18, // 1: dev.lab47.isle.guestapi.ContainerInfo.started_at:type_name -> google.protobuf.Timestamp
	0,  // 2: dev.lab47.isle.guestapi.ProvisionStatus.status:type_name -> dev.lab47.isle.guestapi.ProvisionStatus.Status
	2,  // 3: dev.lab47.isle.guestapi.ProvisionStatus.network_info:type_name -> dev.lab47.isle.guestapi.NetworkInfo
	3,  // 4: dev.lab47.isle.guestapi.ProvisionStatus.container_info:type_name -> dev.lab47.isle.guestapi.ContainerInfo
	19, // 5: dev.lab47.isle.guestapi.ResourceIndexKey.value:type_name -> google.protobuf.Value
	5,  // 6: dev.lab47.isle.guestapi.Resource.id:type_name -> dev.lab47.isle.guestapi.ResourceId
	20, // 7: dev.lab47.isle.guestapi.Resource.resource:type_name -> google.protobuf.Any
	4,  // 8: dev.lab47.isle.guestapi.Resource.provision_status:type_name -> dev.lab47.isle.guestapi.ProvisionStatus
	20, // 9: dev.lab47.isle.guestapi.CreateResourceReq.resource:type_name -> google.protobuf.Any
	7,  // 10: dev.lab47.isle.guestapi.CreateResourceResp.resource:type_name -> dev.lab47.isle.guestapi.Resource
	7,  // 11: dev.lab47.isle.guestapi.UpdateResourceReq.resource:type_name -> dev.lab47.isle.guestapi.Resource
	7,  // 12: dev.lab47.isle.guestapi.UpdateResourceResp.resource:type_name -> dev.lab47.isle.guestapi.Resource
	5,  // 13: dev.lab47.isle.guestapi.ReadResourceReq.id:type_name -> dev.lab47.isle.guestapi.ResourceId
	7,  // 14: dev.lab47.isle.guestapi.ReadResourceResp.resource:type_name -> dev.lab47.isle.guestapi.Resource
	5,  // 15: dev.lab47.isle.guestapi.CheckProvisionReq.id:type_name -> dev.lab47.isle.guestapi.ResourceId
	4,  // 16: dev.lab47.isle.guestapi.CheckProvisionResp.status:type_name -> dev.lab47.isle.guestapi.ProvisionStatus
	5,  // 17: dev.lab47.isle.guestapi.DeleteResourceReq.id:type_name -> dev.lab47.isle.guestapi.ResourceId
	7,  // 18: dev.lab47.isle.guestapi.DeleteResourceResp.resource:type_name -> dev.lab47.isle.guestapi.Resource
	8,  // 19: dev.lab47.isle.guestapi.ResourceAPI.Create:input_type -> dev.lab47.isle.guestapi.CreateResourceReq
	10, // 20: dev.lab47.isle.guestapi.ResourceAPI.Update:input_type -> dev.lab47.isle.guestapi.UpdateResourceReq
	12, // 21: dev.lab47.isle.guestapi.ResourceAPI.Read:input_type -> dev.lab47.isle.guestapi.ReadResourceReq
	14, // 22: dev.lab47.isle.guestapi.ResourceAPI.CheckProvision:input_type -> dev.lab47.isle.guestapi.CheckProvisionReq
	16, // 23: dev.lab47.isle.guestapi.ResourceAPI.Delete:input_type -> dev.lab47.isle.guestapi.DeleteResourceReq
	9,  // 24: dev.lab47.isle.guestapi.ResourceAPI.Create:output_type -> dev.lab47.isle.guestapi.CreateResourceResp
	11, // 25: dev.lab47.isle.guestapi.ResourceAPI.Update:output_type -> dev.lab47.isle.guestapi.UpdateResourceResp
	13, // 26: dev.lab47.isle.guestapi.ResourceAPI.Read:output_type -> dev.lab47.isle.guestapi.ReadResourceResp
	15, // 27: dev.lab47.isle.guestapi.ResourceAPI.CheckProvision:output_type -> dev.lab47.isle.guestapi.CheckProvisionResp
	17, // 28: dev.lab47.isle.guestapi.ResourceAPI.Delete:output_type -> dev.lab47.isle.guestapi.DeleteResourceResp
	24, // [24:29] is the sub-list for method output_type
	19, // [19:24] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_resources_proto_init() }
func file_resources_proto_init() {
	if File_resources_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_resources_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IPAddress); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NetworkInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ContainerInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ProvisionStatus); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResourceIndexKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResourceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateResourceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResourceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateResourceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResourceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReadResourceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckProvisionReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckProvisionResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResourceReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_resources_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteResourceResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_resources_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_resources_proto_goTypes,
		DependencyIndexes: file_resources_proto_depIdxs,
		EnumInfos:         file_resources_proto_enumTypes,
		MessageInfos:      file_resources_proto_msgTypes,
	}.Build()
	File_resources_proto = out.File
	file_resources_proto_rawDesc = nil
	file_resources_proto_goTypes = nil
	file_resources_proto_depIdxs = nil
}
